FROM nginx:1.24.0-alpine3.17
LABEL MAINTAINER="Madhu Akula" INFO="Kubernetes Goat"

COPY kubernetes-goat.png /usr/share/nginx/html/kubernetes-goat.png
COPY index.html /usr/share/nginx/html/index.html
